### ISSUE TITLE
Add plugin system

### ISSUE THREAD

**Issue by jhermann** [Build-The-Web/bootils#3]
- everything is a plugin (a 2nd level section in the config)
- core plugins
- custom plugins
- use https://github.com/mitsuhiko/pluginbase **and** https://github.com/hpk42/pluggy

**Comment by spodkowinski** [comment]
Plugins should be able to control the startup/stop process. E.g. I'd like to create a plugin that can parse the cassandra config file on startup and abort the startup process with a custom message.
